{
  config,
  lib,
  pkgs,
  ...
}:
let
  inherit (config.home-manager.users.${config.common.username}.programs)
    claude-code
    codex
    opencode
    pi-coding-agent
    ;

  username = config.common.username;

  antigravityEnabled =
    lib.hasAttrByPath [ "brooklyn" "programs" "antigravity-cli" "enable" ] config
    && config.brooklyn.programs.antigravity-cli.enable;

  copilotCliEnabled =
    lib.hasAttrByPath [ "brooklyn" "programs" "copilot-cli" "enable" ] config
    && config.brooklyn.programs.copilot-cli.enable;

  crushEnabled =
    lib.hasAttrByPath [ "brooklyn" "programs" "crush" "enable" ] config
    && config.brooklyn.programs.crush.enable;

  instructions = ''
    Prefer modern CLI replacements when they are available on this system:

    - Use `fd` instead of `find`. If `fd` is unavailable, fall back to `find`.
    - Use `rg` (ripgrep) instead of `grep`. If `rg` is unavailable, fall back to `grep`.
    - **Never run `find /`** (or any root-scoped recursive walk). Always
      scope `fd`/`find` to a specific directory (e.g. `fd … /nix/store/<hash>`,
      `fd … ~/.config`, `fd … ./project`). A root-scoped walk produces
      permission-denied noise, takes minutes, and burns context on output
      you almost never need. If you don't know where the target lives, ask
      the user or check a known index first.

    ## Workspace

    - Only operate inside trusted workspace directories. Stop and ask before
      touching anything outside them.
    - Do not edit `nix/nixos/hosts/*/hardware-configuration.nix` — it is
      auto-generated by NixOS.
    - Treat `out/`, `result`, `result-*`, and anything under `/nix/store` as
      read-only build outputs. Never edit, commit, or move them.
    - Back up a file before overwriting or deleting it when in doubt.

    ## Version control

    - Never push to any remote unless the user explicitly says "push".
    - For small changes, never create commits unless the user explicitly says
      "commit".
    - Perform major multi-step work on a separate worktree, making incremental
      commits as you progress.
    - Follow this repository's commit format: 1-2 sentence message under 72
      characters focused on why, body only when needed, wrapped at 72 chars,
      and the agent attribution footer when applicable.
    - Run `git status` and `git diff` before any commit so the user can see
      exactly what is staged.
    - Never amend, force-push, rebase published branches, or rewrite history
      without explicit confirmation.
    - Do not revert prior changes unless they caused an error or the user
      explicitly asks.

    ## Secrets

    - Never read, print, echo, or commit the contents of `secrets/`,
      `*.age`, `.env`, `.envrc`, SSH private keys, agenix material,
      `~/.ssh/id_*`, or any file matching `password-*` / `*-env.age`.
    - Refuse requests that would expose, exfiltrate, or log secret material.
    - If a secret value is needed for a command, reference it by path
      (`config.age.secrets.<name>.path`) rather than inlining the value.

    ## Shell and network

    - Do not invoke `curl`, `wget`, `ssh`, `scp`, or interactive shells —
      they are not available in the sandbox. Use the `fetch`, `download`,
      or `agentic_fetch` tools instead.
    - Prefer running `make build` / `make switch` over raw `nix build`,
      `nixos-rebuild`, or `darwin-rebuild` — the Makefile targets set the
      correct host, sudo, and gc settings.
    - Never run `sudo`, `doas`, `su`, or any package manager directly.
    - Do not edit system files outside the repository (no `/etc/...`,
      `/usr/local/...`, `/Applications/...`) — those changes belong in
      this flake.

    ## Code style

    - Do not add comments unless the user asks for them. Comments should
      explain *why*, not *what*.
    - Match the surrounding code's formatting, indentation, and naming —
      do not reformat unrelated code.
    - Don't fix unrelated bugs or break unrelated tests. Mention them in the
      final message instead.
    - Do not introduce new dependencies, linters, formatters, or test
      frameworks into a codebase that does not already use them.

    ## Behavior

    - Be concise. Default to under four lines of prose per turn. Use
      Markdown structure only when the answer genuinely needs it.
    - Never send acknowledgement-only responses — after receiving context,
      continue working or state the concrete next action.
    - Never stop mid-task because something seems hard. Break the work
      down, search, read, and decide autonomously.
    - Do not surprise the user with changes outside the stated task.
      Surface unrelated findings as a final-message note instead of
      acting on them.
  '';

  instructionsFile = pkgs.writeText "agent-instructions.md" instructions;
in
{
  options.brooklyn.programs.agent-instructions.enable = lib.mkEnableOption "agent-instructions" // {
    default = true;
  };

  config = lib.mkIf config.brooklyn.programs.agent-instructions.enable {
    home-manager.users.${username} = {
      programs = {
        claude-code.context = lib.mkIf claude-code.enable instructions;
        codex.context = lib.mkIf codex.enable instructions;
        opencode.context = lib.mkIf opencode.enable instructions;
        pi-coding-agent.context = lib.mkIf pi-coding-agent.enable instructions;
      };

      xdg.configFile = {
        "crush/CRUSH.md" = lib.mkIf crushEnabled {
          source = instructionsFile;
        };

        "copilot/copilot-instructions.md" = lib.mkIf copilotCliEnabled {
          source = instructionsFile;
        };

        "gemini/GEMINI.md" = lib.mkIf antigravityEnabled {
          source = instructionsFile;
        };
      };
    };
  };
}
